### PR TITLE
FromRequest trait receive &Req.

### PR DESCRIPTION
**Pull request by fakeshadow**

### CODE REVIEW

**Comment by fakeshadow** [comment]
@aliemjay 
What do you think of this pattern. Where FromRequest always receive &Req type as argument.
I added a new combinator to mutate the type that passed to handler_service so this should work with partial or complete internal mutability of the Req type.
```rust
use std::{cell::RefCell, convert::Infallible, future::Future};

use xitca_http::{
    body::{RequestBody, ResponseBody},
    http::{Request, Response},
    util::service::{get, handler_service, FromRequest, Router},
    HttpServiceBuilder,
};
use xitca_service::{fn_service, ServiceFactoryExt};

#[tokio::main]
async fn main() -> std::io::Result<()> {
    xitca_server::Builder::new()
        .bind("test", "localhost:8080", || {
            let router = Router::new().insert("/", get(handler_service(index)));
            HttpServiceBuilder::new(
                fn_service(|req: Request<RequestBody>| async move { Ok(req.map(RefCell::new)) })
                    .and_then(router),
            )
        })?
        .build()
        .await
}

async fn index(Extract(p1): Extract<&str>) -> Response<ResponseBody> {
    assert_eq!(&*p1, "/");
    Response::new("Hello,World!".into())
}

struct Extract<T>(T);

impl<'a> FromRequest<'a, Request<RefCell<RequestBody>>> for Extract<&'a str> {
    type Type<'f> = Extract<&'f str>;
    type Error = Infallible;
    type Future = impl Future<Output = Result<Self, Self::Error>>;

    fn from_request(req: &'a Request<RefCell<RequestBody>>) -> Self::Future {
        async move { Ok(Extract(req.uri().path())) }
    }
}
```

**Comment by aliemjay** [comment]
Yep, that's better.

And I think what we have now is already generic to work with FromRequest<&mut Req>, I'll check it out.

**Comment by fakeshadow** [comment]
How would `FromRequest<&mut Req>` work? Can it be used in concurrent extract futures?

**Comment by aliemjay** [comment]
> How would `FromRequest<&mut Req>` work? Can it be used in concurrent extract futures?

No It doesn't allow mutable access in extractor or handler anyway. I'm just stating this code is generic over &mut Request which then would only allows mutable access in middlewares

**Comment by aliemjay** [comment]
ehat I say is that we can still have this for &mut Request:
```rust
impl<'a> FromRequest<'a, &'a mut Req> for &'a Req {
    type Type<'f> = &'f Req;
    type Error = Infallible;
    type Future = impl Future<Output = Result<Self, Self::Error>>;

    fn from_request(req: &'a &'a mut Req) -> Self::Future {
        async move { Ok(req) }
    }
}
```

but not this:
```rust
impl<'a> FromRequest<'a, &'a mut Req> for &'a mut Req {
    type Type<'f> = Extract<&'f str>;
    type Error = Infallible;
    type Future = impl Future<Output = Result<Self, Self::Error>>;

    fn from_request(req: &'a &'a mut Req) -> Self::Future {
        async move { Ok(req) }
    }
}
```

**Pull request merged**
